package org.DenWorker.Java_Core._3_Exceptions._3_2_Exception_Handling_Try_Catch;

public class Task_3_2_3 {
    public static void main(String[] args) {
        System.out.println("Если в блоке try вызван System.exit(0).");
        System.out.println("Если во время исполнения блока try виртуальная машина выполнила недопустимую операцию и будет закрыта");
    }
}
